### ISSUE TITLE
Broken URL in README.md

### ISSUE THREAD

**Issue by RichardDavies** [aws-samples/aws-cognito-java-desktop-app#11]
This URL in the readme is broken: https://sid343.reinvent-workshop.com/

**Comment by omblivion** [comment]
up

**Comment by RichardDavies** [comment]
Hmm. Still not loading for me. Tried it from two different networks and no go.

**Comment by koiker** [comment]
Fixed, can you test again to confirm?

**Comment by omblivion** [comment]
The connection has timed out

The server at sid343.reinvent-workshop.com is taking too long to respond.

I seems just offline for me.

**Comment by RichardDavies** [comment]
Interesting... just discovered that http://sid343.reinvent-workshop.com/ works, but https://sid343.reinvent-workshop.com/ does not. 

It appears the readme link has been changed from https to http so that resolves the issue.
