### ISSUE TITLE
Unable to verify secret hash for client cognito

### ISSUE THREAD

**Issue by garrido-mosqueira** [aws-samples/aws-cognito-java-desktop-app#3]
When the Client Secret Key is use, there is no way to authorise the user. 

I was able to SingUp with the client secret adding this line to the VerifyAccessCode() method:
confirmSignUpRequest.**setSecretHash**(calculateSecretHash(CLIENTAPP_ID, SECRET, username));

But when is time to SingIn the error rise when we are trying to get the Challenge Response.

RespondToAuthChallengeResult result = cognitoIdentityProvider.respondToAuthChallenge(challengeRequest);

Any thoughts?

**Comment by singh96** [comment]
Any update on this?

**Comment by garrido-mosqueira** [comment]
Hi!... I forgot about this issue.  I fixed it adding the Secret Hash in the method userSrpAuthRequest of the AuthenticationHelper class. 

```
if(secretHash!=null && !secretHash.isEmpty()) {
         srpAuthResponses.put("SECRET_HASH", secretHash);
}
```

So this way you send the SecretHash in the Challenge Responses.
