### ISSUE TITLE
idprovider

### ISSUE THREAD

**Issue by SergeVil** [aws-samples/aws-cognito-java-desktop-app#4]
Hello,

Great tutorial. I have the question about idprovider in 

Credentials GetCredentials(String idprovider, String id) { }

What should it be?

Thank you,
Serge

**Comment by SergeVil** [comment]
Found the answer

        String result = cognitoHelper.ValidateUser("user", "XXXXX");
        if (result != null) {
            System.out.println("User is authenticated:" + result);
            JSONObject payload = CognitoJWTParser.getPayload(result);
            String provider = payload.get("iss").toString().replace("https://", "");

            Credentials credentails = cognitoHelper.GetCredentials(provider, result);
				
            System.out.println(credentails);
        }

**Comment by koiker** [comment]
Good to hear that you are enjoying the samples!
